version: 0.2

phases:
  install:
    commands:
      - echo Updating
  pre_build:
    commands:
      - echo Restoring dependencies...
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Clivis code
      - dotnet publish 
      - ls -l bin/Debug/netcoreapp2.0/publish/
  post_build:
    commands:
      - echo Post Build completed on `date`
artifacts:
  files:
    - bin/Debug/netcoreapp2.0/publish/clivisapi.dll